import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

// One config for the app and the shared packages. Mirrors Cosmos's
// app/eslint.config.js, including the UI copy rules.
export default tseslint.config(
  {
    // Generated by ts-rs from atlas-common; regenerate rather than edit.
    ignores: ['**/dist', '**/node_modules', 'app/src/generated', 'target'],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // `_`-prefixed bindings drop keys when destructuring a record.
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // Empty catch blocks are deliberate: localStorage access must never
      // break a render.
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    files: ['*.config.{js,ts}', 'app/*.config.{js,ts}'],
    languageOptions: { globals: globals.node },
  },
  {
    // Copy rules for user-facing text: no em dashes or typographic entities.
    files: ['app/src/pages/**/*.tsx', 'app/src/components/**/*.tsx', 'app/src/layouts/**/*.tsx'],
    ignores: ['**/*.test.tsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'JSXText[value=/—|’|“|”/]',
          message: 'Avoid em dashes and typographic entities in UI text.',
        },
        {
          selector: 'Literal[value=/—/]',
          message: 'Avoid em dashes in UI strings.',
        },
        {
          selector: 'TemplateElement[value.raw=/—/]',
          message: 'Avoid em dashes in UI strings.',
        },
      ],
    },
  },
  {
    // Vendored shadcn primitives, listed last so these win. The shadcn CLI
    // regenerates them, so rewriting them for the React Compiler rules would
    // be undone by the next `shadcn add`.
    files: ['packages/sunstead-ui/src/components/ui/**'],
    rules: {
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },
);
